"""Versioned PDF and DOCX reports rendered from one canonical verdict snapshot.

Two kinds. A FIELD copy is generated by the capturing officer for their own use and is
watermarked as not legally finalised; it never changes the scan's status, so the
inspection stays open to correction, re-evaluation and override. A FINALIZED report is
signed by a reviewing officer and closes the scan.

`content_sha256` hashes the snapshot, never the rendering — so how a report looks can be
changed freely, and the same inspection re-rendered later still hashes the same.
"""
from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from typing import Any

from lmpc.engine import ocr_models
from lmpc.engine.extract import ACCUSE, FLOOR, LEGIBLE, MARGIN
from lmpc.engine.ocr import CAP_RATIO

from ..api.errors import ApiError
from ..report import docx_writer, html, investigation, sections, thumbnails
from .object_store import ObjectStore

DOCX_MEDIA = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
TEMPLATE_VERSION = 2


class ReportService:
    def __init__(self, scans, objects: ObjectStore, rulepack: dict, *, max_edge: int,
                 git_sha: str = "", container_digest: str = "", investigations=None):
        self.scans = scans
        self.objects = objects
        self.rulepack = rulepack
        self.max_edge = max_edge
        self.git_sha = git_sha
        self.container_digest = container_digest
        self.investigations = investigations

    def finalize(self, scan_id: str, *, reviewed_by: str | None = None,
                 kind: str = "FINALIZED", generated_by: str | None = None) -> dict:
        scan = self.scans.get(scan_id)
        if not scan.latest_evaluations():
            raise ApiError("E_CONFLICT", "the scan has no completed evaluation batch")
        if any(item["outcome"] == "SYSTEM_ERROR" for item in scan.latest_evaluations()):
            raise ApiError("E_CONFLICT", "unresolved SYSTEM_ERROR results block finalization")
        version = self.scans.next_report_version(scan_id, kind=kind)
        snapshot = _snapshot(scan, self.rulepack, self._investigation_of(scan))
        content_sha256 = _hash(snapshot)
        manifest = self._manifest(scan, content_sha256, kind, generated_by)
        pdf, docx = self._render(snapshot, version, kind, content_sha256)
        prefix = f"reports/{scan_id}/{kind.lower()}/{version}"
        keys = self._store(prefix, pdf, docx)
        return self.scans.save_report(
            scan_id, version=version, overall_status=scan.overall,
            pdf_storage_key=keys[0], docx_storage_key=keys[1],
            content_sha256=content_sha256, manifest=manifest,
            reviewed_by=reviewed_by, report_kind=kind, generated_by=generated_by)

    def finalize_investigation(self, investigation_id: str, *, kind: str,
                               generated_by: str, principal) -> dict:
        """One document covering the whole folder."""
        folder = self.investigations.get(principal, investigation_id)
        scans = self.investigations.scan_details(principal, investigation_id)
        if not scans:
            raise ApiError("E_CONFLICT", "this investigation has no completed scans yet")
        version = self.scans.next_investigation_report_version(investigation_id, kind=kind)
        snapshot = {"investigation": folder, "scans": scans,
                    "rulepack": {"version": self.rulepack["version"],
                                 "sha256": self.rulepack["sha256"],
                                 "current_to":
                                     self.rulepack["currency"]["newest_instrument"]},
                    "disclosures": [item["text"] for item in
                                    self.rulepack["currency"]["acknowledged_gaps"]]}
        content_sha256 = _hash(snapshot)
        model = investigation.sections(
            folder, scans, version=version, kind=kind, content_hash=content_sha256,
            disclosures=snapshot["disclosures"], rulepack=snapshot["rulepack"])
        from weasyprint import HTML
        pdf = HTML(string=html.render(model, kind=kind)).write_pdf()
        docx = docx_writer.render(model, kind=kind)
        # A distinct prefix: the object store is create-only and raises on collision.
        keys = self._store(
            f"reports/investigations/{investigation_id}/{kind.lower()}/{version}",
            pdf, docx)
        return self.scans.save_investigation_report(
            investigation_id, version=version,
            overall_status=("NON_COMPLIANT" if any(
                scan.get("overall") == "NON_COMPLIANT" for scan in scans) else "COMPLIANT"),
            pdf_storage_key=keys[0], docx_storage_key=keys[1],
            content_sha256=content_sha256,
            manifest={"investigation_id": investigation_id, "report_kind": kind,
                      "generated_by": generated_by, "scan_count": len(scans),
                      "evaluated_at": datetime.now(UTC).isoformat(),
                      "renderer": {"template_version": TEMPLATE_VERSION},
                      "rulepack": snapshot["rulepack"],
                      "scans": [{"scan_id": scan["id"],
                                 "overall": scan.get("overall")} for scan in scans]},
            report_kind=kind, generated_by=generated_by)

    def download(self, report_id: str, format_: str) -> tuple[bytes, str, str]:
        report = self.scans.get_report(report_id)
        if format_ == "pdf":
            return self.objects.read(report["pdf_storage_key"]), "application/pdf", "report.pdf"
        if format_ == "docx":
            return self.objects.read(report["docx_storage_key"]), DOCX_MEDIA, "report.docx"
        raise ApiError("E_VALIDATION", "format must be pdf or docx")

    # ---- rendering ---------------------------------------------------------------

    def _render(self, snapshot: dict, version: int, kind: str,
                content_sha256: str) -> tuple[bytes, bytes]:
        from weasyprint import HTML

        model = sections.scan_sections(
            snapshot, version=version, kind=kind, content_hash=content_sha256)
        pictures = thumbnails.render(self.objects, snapshot["images"])
        for item in model:
            if item["kind"] == "images":
                item["images"] = pictures
        pdf = HTML(string=html.render(model, kind=kind)).write_pdf()
        return pdf, docx_writer.render(model, kind=kind)

    def _store(self, prefix: str, pdf: bytes, docx: bytes) -> tuple[str, str]:
        pdf_key, docx_key = f"{prefix}/report.pdf", f"{prefix}/report.docx"
        self.objects.put_immutable(
            pdf_key, pdf, "application/pdf", hashlib.sha256(pdf).hexdigest())
        self.objects.put_immutable(
            docx_key, docx, DOCX_MEDIA, hashlib.sha256(docx).hexdigest())
        return pdf_key, docx_key

    def _investigation_of(self, scan) -> dict:
        folder = getattr(scan, "investigation_id", None)
        if not folder or self.investigations is None:
            return {}
        try:
            return self.investigations.db.get(folder) if self.investigations.db else {}
        except ApiError:
            return {}

    def _manifest(self, scan, content_sha256: str, kind: str,
                  generated_by: str | None) -> dict:
        models = [{"name": name, "sha256": digest} for name, digest in
                  sorted(ocr_models.entry().get("devanagari", {}).items())]
        return {
            "scan_id": scan.id, "evaluation_batch": scan.batch,
            "evaluated_at": datetime.now(UTC).isoformat(),
            "content_sha256": content_sha256,
            "report_kind": kind, "generated_by": generated_by,
            # The template version records how it was drawn. It is deliberately in the
            # manifest and not the snapshot: a redesign must never change a content hash.
            "renderer": {"template_version": TEMPLATE_VERSION},
            "rulepack": {"version": scan.rulepack_version,
                         "sha256": scan.rulepack_sha256},
            "models": models,
            "params": {"MAX_EDGE": self.max_edge, "CAP_RATIO": CAP_RATIO,
                       "FLOOR": FLOOR, "MARGIN": MARGIN,
                       "LEGIBLE": LEGIBLE, "ACCUSE": ACCUSE},
            "code": {"git_sha": self.git_sha, "container_digest": self.container_digest},
            "inputs": [{"storage_key": image.storage_key, "sha256": image.sha256,
                        "max_edge_used": image.max_edge_used} for image in scan.images],
        }


def _hash(snapshot: dict) -> str:
    canonical = json.dumps(snapshot, sort_keys=True, separators=(",", ":"),
                           ensure_ascii=False).encode()
    return hashlib.sha256(canonical).hexdigest()


def _snapshot(scan, pack: dict, investigation: dict | None = None) -> dict[str, Any]:
    body: dict[str, Any] = {
        "identification": {"scan_id": scan.id, "category": scan.category,
                           "mode": scan.mode},
        "overall": scan.overall,
        "captured_at": scan.captured_at,
        "coverage": {"asserted": scan.coverage_asserted, "panels": scan.panels},
        "declarations": scan.latest_declarations(),
        "evaluations": scan.latest_evaluations(),
        "disclosures": [item["text"] for item in
                        pack["currency"]["acknowledged_gaps"]],
        "rulepack": {"version": scan.rulepack_version, "sha256": scan.rulepack_sha256,
                     "current_to": pack["currency"]["newest_instrument"]},
        "images": [{"panel": image.panel_label, "sha256": image.sha256,
                    "storage_key": image.storage_key} for image in scan.images],
    }
    remark = (scan.metadata or {}).get("officer_remarks")
    if remark:
        body["notes"] = [{"body": remark, "author": "Capturing officer",
                          "created_at": None}]
    if investigation:
        body["investigation"] = {
            "id": investigation.get("id"), "name": investigation.get("name"),
            "subject_brand": investigation.get("subject_brand"),
            "location_text": investigation.get("location_text"),
            "investigation_type": investigation.get("investigation_type"),
        }
    return body
