/* Shared widgets, moved verbatim from App.tsx so every screen file can reach them. */
import { ActivityIndicator, Modal, Pressable, SafeAreaView, ScrollView, Text, TextInput, View } from "react-native";
import type * as React from "react";
import type { RuleDetail } from "../types";
import { styles } from "../theme";

export function Header({title,action,onAction}:{title:string;action:string;onAction:()=>void}){return <View style={styles.header}><Logo compact/><Text style={styles.headerTitle}>{title}</Text><Pressable onPress={onAction}><Text style={styles.link}>{action}</Text></Pressable></View>;}
export function Logo({light=false,compact=false}:{light?:boolean;compact?:boolean}){return <View style={[styles.logo,light&&styles.logoLight,compact&&styles.logoCompact]}><Text style={[styles.logoText,light&&styles.logoTextLight]}>LM</Text></View>;}
export function Primary({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" style={[styles.primary,disabled&&styles.disabled]} disabled={disabled} onPress={onPress}><Text style={styles.primaryText}>{label}</Text></Pressable>;}
export function Field(props:React.ComponentProps<typeof TextInput>&{label:string}){const {label,...input}=props;return <View><Text style={styles.label}>{label}</Text><TextInput style={styles.input} placeholderTextColor="#839087" {...input}/></View>;}
export function ChoiceRow({values,selected,select}:{values:string[];selected:string;select:(value:string)=>void}){return <View style={styles.choiceRow}>{values.map(value=><Choice key={value} value={value} selected={selected===value} onPress={()=>select(value)}/>)}</View>;}
export function Choice({value,selected,onPress}:{value:string;selected:boolean;onPress:()=>void}){return <Pressable style={[styles.choice,selected&&styles.choiceOn]} onPress={onPress}><Text style={[styles.choiceText,selected&&styles.choiceTextOn]}>{value.replaceAll("_"," ")}</Text></Pressable>;}
export function Outcome({value}:{value:string}){const tone=value==="COMPLIANT"||value==="PASS"||value==="COMPLETE"?styles.pillPass:value==="NON_COMPLIANT"||value==="FAIL"||value==="FAILED"||value==="SYSTEM_ERROR"?styles.pillFail:value==="REVIEW_REQUIRED"||value==="INCOMPLETE_EVIDENCE"?styles.pillWarn:styles.pillInfo;return <View style={[styles.pill,tone]}><Text style={styles.pillText}>{value.replaceAll("_"," ")}</Text></View>;}
export function Loading({label}:{label:string}){return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator size="large" color="#1e6647"/><Text style={styles.bodyCenter}>{label}</Text></View></SafeAreaView>;}
export function FatalScreen({title="LMPC Field could not start",message,retry}:{title?:string;message:string;retry:()=>void}){return <SafeAreaView style={styles.safe}><View style={styles.center}><Logo/><Text style={styles.h1}>{title}</Text><Text style={styles.bodyCenter}>Your captured evidence has not been removed. Try opening the app again; if this continues, share the diagnostic below with support.</Text><Text selectable style={styles.fatalCode}>{message||"Unknown startup error"}</Text><Primary label="Try again" onPress={retry}/></View></SafeAreaView>;}
export function RuleModal({rule,close}:{rule:RuleDetail|null;close:()=>void}) {return <Modal visible={!!rule} animationType="slide" presentationStyle="pageSheet" onRequestClose={close}><SafeAreaView style={styles.safe}>{rule&&<ScrollView contentContainerStyle={styles.modalPage}><View style={styles.sectionHead}><Text style={styles.eyebrow}>{rule.clause}</Text><Pressable onPress={close}><Text style={styles.link}>Close</Text></Pressable></View><Text style={styles.h1}>{rule.title}</Text><RuleSection title="What the rule requires" text={rule.requirement}/><RuleSection title="What the system did" text={rule.method}/><RuleSection title="Evidence needed" text={rule.evidence_needed}/>{rule.important_limits.length>0&&<RuleSection title="Important limits" text={rule.important_limits.join("\n")}/>}<View style={styles.info}><Text style={styles.infoText}>{rule.non_normative_notice}</Text></View></ScrollView>}</SafeAreaView></Modal>;}
function RuleSection({title,text}:{title:string;text:string}){return <View style={styles.ruleSection}><Text style={styles.nextLabel}>{title}</Text><Text style={styles.nextText}>{text}</Text></View>;}
